// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.23.3
// source: modules/auth/authPb/authPb.proto

package Go_MicroService

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AuthGrpcServiceClient is the client API for AuthGrpcService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthGrpcServiceClient interface {
	AccessToKenSearch(ctx context.Context, in *AccessToKenSearchReq, opts ...grpc.CallOption) (*AccessToKenSearchRes, error)
	RoleCount(ctx context.Context, in *RoleCountReq, opts ...grpc.CallOption) (*RoleCountRes, error)
}

type authGrpcServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthGrpcServiceClient(cc grpc.ClientConnInterface) AuthGrpcServiceClient {
	return &authGrpcServiceClient{cc}
}

func (c *authGrpcServiceClient) AccessToKenSearch(ctx context.Context, in *AccessToKenSearchReq, opts ...grpc.CallOption) (*AccessToKenSearchRes, error) {
	out := new(AccessToKenSearchRes)
	err := c.cc.Invoke(ctx, "/AuthGrpcService/AccessToKenSearch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authGrpcServiceClient) RoleCount(ctx context.Context, in *RoleCountReq, opts ...grpc.CallOption) (*RoleCountRes, error) {
	out := new(RoleCountRes)
	err := c.cc.Invoke(ctx, "/AuthGrpcService/RoleCount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthGrpcServiceServer is the server API for AuthGrpcService service.
// All implementations must embed UnimplementedAuthGrpcServiceServer
// for forward compatibility
type AuthGrpcServiceServer interface {
	AccessToKenSearch(context.Context, *AccessToKenSearchReq) (*AccessToKenSearchRes, error)
	RoleCount(context.Context, *RoleCountReq) (*RoleCountRes, error)
	mustEmbedUnimplementedAuthGrpcServiceServer()
}

// UnimplementedAuthGrpcServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAuthGrpcServiceServer struct {
}

func (UnimplementedAuthGrpcServiceServer) AccessToKenSearch(context.Context, *AccessToKenSearchReq) (*AccessToKenSearchRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AccessToKenSearch not implemented")
}
func (UnimplementedAuthGrpcServiceServer) RoleCount(context.Context, *RoleCountReq) (*RoleCountRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RoleCount not implemented")
}
func (UnimplementedAuthGrpcServiceServer) mustEmbedUnimplementedAuthGrpcServiceServer() {}

// UnsafeAuthGrpcServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthGrpcServiceServer will
// result in compilation errors.
type UnsafeAuthGrpcServiceServer interface {
	mustEmbedUnimplementedAuthGrpcServiceServer()
}

func RegisterAuthGrpcServiceServer(s grpc.ServiceRegistrar, srv AuthGrpcServiceServer) {
	s.RegisterService(&AuthGrpcService_ServiceDesc, srv)
}

func _AuthGrpcService_AccessToKenSearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccessToKenSearchReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthGrpcServiceServer).AccessToKenSearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AuthGrpcService/AccessToKenSearch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthGrpcServiceServer).AccessToKenSearch(ctx, req.(*AccessToKenSearchReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthGrpcService_RoleCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoleCountReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthGrpcServiceServer).RoleCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AuthGrpcService/RoleCount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthGrpcServiceServer).RoleCount(ctx, req.(*RoleCountReq))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthGrpcService_ServiceDesc is the grpc.ServiceDesc for AuthGrpcService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthGrpcService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "AuthGrpcService",
	HandlerType: (*AuthGrpcServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AccessToKenSearch",
			Handler:    _AuthGrpcService_AccessToKenSearch_Handler,
		},
		{
			MethodName: "RoleCount",
			Handler:    _AuthGrpcService_RoleCount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "modules/auth/authPb/authPb.proto",
}
